### ISSUE TITLE
Ecommerce "dataLayer"

### ISSUE THREAD

**Issue by kolyasapphire** [mustafauysal/yandex-metrica#41]
Hi! It would be useful to add an optional 'ecommerce' parameter in the tracker templates for compatibility with ecommerce analytics and for future WooCommerce integration - #37 

I believe the default one is:
`ecommerce: "dataLayer"`

**Comment by mustafauysal** [comment]
hi @kolyasapphire 

Thanks for the feedback. I will consider adding in the next version.

**Comment by mustafauysal** [comment]
@kolyasapphire new version of the plugin has been released, and it supports dispatching e-commerce data
