### ISSUE TITLE
Plugin Update Failed

### ISSUE THREAD

**Issue by geektaboo** [mustafauysal/yandex-metrica#42]
Hi!

I can't update Yandex-metrica plugin on my [games blog](https://incestly.com). My current version is 1.7. What's am i doing wrong? Thanks!
![joxi_screenshot_1567449186062](https://user-images.githubusercontent.com/54816955/64130259-0f6ac000-cd76-11e9-9b6e-5d589f57ece2.png)

**Comment by ildarkhasanshin** [comment]
check permissions on directories
should be 755
